spring:
  application:
    name: blog-app
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./testdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
    port : 4343


